### PR TITLE
Scannon

### PR DESCRIPTION
**Pull request by cann0010**
Numerous changes:
- Remove bell alert & header linking to legacy site;
- Remove text references to legacy site;
- Slight change in link text color, for better readability;
- Change menu item "Contact" to "About & Contact", and add information about submitting data and citing LIS;
- Add news item about the legacy decommissioning and recent data updates.

### CODE REVIEW

**Comment by sammyjava** [comment]
You've removed the bell from the header, but the extra blurb on the top remains:
image

**Comment by alancleary** [comment]
> You've removed the bell from the navigation bar, but the extra blurb on the top remains: image

@cann0010 Delete the alert by removing the content of _includes/alerts.html, but don't delete the file. The bell will automatically disappear if this file is empty, so you should not comment out the bell in the navbar, i.e. [this change](https://github.com/legumeinfo/jekyll-legumeinfo/blob/a6d07c4e137c752d04395192e1d525d791a49efc/_includes/navbar.html#L75) should be reverted.

**Comment by cann0010** [comment]
I believe the bell reversion and alerts.html removal is done. If you would check again, please, @alancleary and/or @sammyjava

**Review by sammyjava — APPROVED** [review]
Looks good to me!

**Pull request merged**
