### PR TITLE
updates for adding pangene lookup component

### PR DESCRIPTION
**Pull request by adf-ncgr**
per @alancleary example from starter site

### CODE REVIEW

**Comment by alancleary** [comment]
@adf-ncgr The theme and whatnot seems to be working as expected but I'm getting a socket hang up error from the GraphQL server when the pangene component tries to get data for the form. Maybe the server needs to swapped to Bun again, despite its known issues...

Also, I think "lookup" in the "Pangene lookup Tool" `tools.yml` entry should be capitalized.

**Comment by adf-ncgr** [comment]
yes, I started experiencing the socket hangup after a while too and had the same thought about bun. Let me see about that

**Comment by adf-ncgr** [comment]
I stood up a temporary non-officially released version of the graphql server using bun but will switch it to an official release when that's ready. fixed capitalization, will merge once @alancleary gives me the ok (or I get tired of waiting for it)

**Comment by adf-ncgr** [comment]
merged without further review. mea culpa!

**Comment by alancleary** [comment]
Sorry for the delay. All seems to be functioning as intended, although I've found a bug in the component. Not a blocker but worth an issue in the web component repo.

**Pull request merged**
