### PR TITLE
Use theme

### PR DESCRIPTION
**Pull request by sammyjava**
This is a PR on the updates I've done to have the site use the theme again. This includes moving Google Analytics to the theme. I think it's "mature."

### CODE REVIEW

**Comment by sammyjava** [comment]
I'd say let's punch this into main and have the production site running on the theme, and then move forward. But probably requires a careful review, @alancleary when you get a chance.

**Comment by sammyjava** [comment]
Updated with move of announcements and blog to theme.

**Comment by sammyjava** [comment]
This keeps chugging along. I've removed all mention of "announcements" and moved those posts under news. I've put "categories: announcements" on those posts. However, right now, the home page gets a bunch of announcements rather than "general" news posts - maybe we need to update the theme's news card to treat "general" and "announcements" differently. But that's in the theme, not here.

**Comment by sammyjava** [comment]
This is a fairly mature PR at this point, but I suppose maybe some more "use theme" updates will be coming? Not sure. It works against the current theme main branch.

**Comment by alancleary** [comment]
> This is a fairly mature PR at this point, but I suppose maybe some more "use theme" updates will be coming? Not sure. It works against the current theme main branch.

I think we should definitely get the [GraphQL scripts issue](https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/39) resolved before merging. More generally, the [version 1.0.0 release](https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/35) of the theme seems like a good time to switch legumeinfo to the theme. There's not too much left to do there. Just busy work that someone needs to find the time for.

**Comment by sammyjava** [comment]
> Perhaps just personal preference, but a couple customizations in this repo might be worth backporting to the theme; e.g.:
> 
>     * Tool description tooltips
>       https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/_includes/tools-menu.html#L8
> 
>     * reading-width layout for news items:
>       https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/_layouts/news-item.html#L2

Fine with me but I'll defer to @alancleary on it. I do parallel updates yanking stuff from jekyll-legumeinfo on this branch and putting them into the theme with a specific branch. Happy to hit these.

**Comment by alancleary** [comment]
> > Perhaps just personal preference, but a couple customizations in this repo might be worth backporting to the theme; e.g.:
> > ```
> > * Tool description tooltips
> >   https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/_includes/tools-menu.html#L8
> > 
> > * reading-width layout for news items:
> >   https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/_layouts/news-item.html#L2
> > ```
> 
> Fine with me but I'll defer to @alancleary on it. I do parallel updates yanking stuff from jekyll-legumeinfo on this branch and putting them into the theme with a specific branch. Happy to hit these.

These both sound good to me. Thanks for volunteering @sammyjava.

Regarding getting this PR reviewed/merged, I'm waiting for the [version 1.0.0 release](https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/35) of the theme, which I'm aiming to have done before the holidays!

**Comment by sammyjava** [comment]
As for the `news-item` layout, that's already gone from this branch. The only layout remaining in `jekyll-legumeinfo/_layouts` is `collection.html` which is used by the _data page generator (somehow).

@alancleary I've got the updated `tools-menu.html` running in the theme with the name-sort and tooltips on my dev site, but it turns out that neither of those things ever worked. The tools are not sorted by name and there are no tooltips, both on dev and on the production site. Seems like we need to edit this file to make those features work:
```
[shokin@jekyll-dev-vm jekyll-legumeinfo]$ cat ./_themes/jekyll-theme-legumeinfo/_includes/tools-menu.html
<h3>Tools</h3>
{% if site.data.tools %}
{% assign groups = site.data.tools | group_by: "category" | sort: "name" %}
{% for group in groups %}
<ul class="uk-nav uk-nav-default tm-nav uk-margin-top">
  <li class="uk-nav-header">{{ group.name }}</li>
  {% for item in group.items | sort: "name" %}
  <li uk-tooltip="title: {{ item.description }}"><a href="{{ item.url }}">{{ item.name }}</a></li>
  {% endfor %}
</ul>
{% endfor %}
{% endif %}
```
The relevant theme branch is `tools-menu-sort-and-tooltips`.

**Comment by sammyjava** [comment]
(Note: I have switched the theme news-item layout to `reading-width`, I was confused for a minute in that previous comment.)

**Comment by sammyjava** [comment]
@alancleary I clearly have not had enough coffee yet today. I was looking at the menu, not the left hand side of the site. It is indeed being sorted properly with tooltips on my dev site.

**Comment by sammyjava** [comment]
I yanked `uk-link-reset` from the local files, and since `navbar.html` is identical to the theme's, I yanked that file.

**Pull request merged**
