### PR TITLE
dev -> main for deployment on staging site

### PR DESCRIPTION
**Pull request by sammyjava**
This PR follows Nathan's deployment strategy for getting code up to https://jekyll-stage.legumeinfo.org :

1. Commits to the "main" branch of this repo trigger a static site build that gets deployed to the "jekyll-stage.legumeinfo.org" branch, and is hosted by GitHub Pages at https://jekyll-stage.legumeinfo.org .
2. On tag (or release), the tagged commit is built / deployed to the "www.legumeinfo.org" branch (or "main", if that's the preference) of the legumeinfo/legumeinfo.org repo (which is currently just used for old issues). That branch is used to host www.legumeinfo.org (and legumeinfo.org) via GitHub Pages.

There are two ways that updates get staged:
1. Content updates are merged directly into "main" from an author's branch: things like news items, typos, regular old Jekyll content stuff (which hopefully happens reasonably often).
2. Code and other major updates are first merged into "dev" and QCed. Then, when "dev" looks ready for prime time, it is merged into "main" for final staging/QC on https://jekyll-stage.legumeinfo.org.

I've got a jekyll-dev.lis.ncgr.org mounted for viewing the "dev" branch (git pulling every 10 mins), but it probably makes sense to have another GitHub Page hosting "dev" on jekyll-dev.legumeinfo.org, instead, so we hit any GitHub Pages related issues at the "dev" level. @nathanweeks ponder this.

One expects that "main" (the staging site) is almost always promoted rapidly to the production site without changes. There is no slow "monthly rollover" concept, we promote stage whenever it looks good, which could be, for example, minutes after a date has been fixed in a meeting announcement.

### CODE REVIEW

**Comment by sammyjava** [comment]
(Note that the main purpose of this PR is to get the ball rolling on https://jekyll-stage.legumeinfo.org/ and to establish the deployment process. There's nothing particularly interesting about the code itself, it's just the latest iteration of loading in the description files under TAXA, plus a bunch of theme overrides that could, potentially, make it into the theme itself if deemed of general interest.)

**Comment by sammyjava** [comment]
@nathanweeks this one's for you to merge when you've got jekyll-stage.legumeinfo.org set up (in case that wasn't clear). Thanks!

**Comment by alancleary** [comment]
> Commits to the "main" branch of this repo trigger a static site build that gets deployed to the "jekyll-stage.legumeinfo.org" branch, and is hosted by GitHub Pages at https://jekyll-stage.legumeinfo.org .

It may be worth employing branch restrictions on main so no one (I'm definitely liable to do this) doesn't absentmindedly push directly to main.

**Comment by sammyjava** [comment]
Perhaps, but it is still just the staging site, mistakes can be backed out. The production site will be updated by highly authorized personnel, presumably with some tag/release update each time (I like a date-hour format). I do want a clear and easy path to updating the staging site that doesn't require busy people to step away from their work.

**Comment by nathanweeks** [comment]
> Perhaps, but it is still just the staging site, mistakes can be backed out. The production site will be updated by highly authorized personnel, presumably with some tag/release update each time (I like a date-hour format). I do want a clear and easy path to updating the staging site that doesn't require busy people to step away from their work.

There was discussion on the use of tags (with the consensus being in some CalVer format) in https://github.com/legumeinfo/jekyll-legumeinfo/issues/4

> In fact, this is an advantage with production running off a different repo, so it's clear that ANYTHING on any branch of jekyll-legumeinfo does NOT go directly to the production site. I hadn't appreciated this before, but it's a good thing, and now I'm a fan of this deployment approach.

Using a different repo for the production site also makes it feasible to host using GitHub Pages (which only allows at most one [custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site) for a given repo). So a GitHub Actions workflow could build the "main" branch of this repo & deploy the resulting static site in a different branch (either the conventional "gh-pages" for out-of-the-box GitHub Pages builds, or since this is site would be deployed via a custom workflow, perhaps a more-explicit "jekyll-stage.legumeinfo.org" branch)?

**Comment by sammyjava** [comment]
Ahh, I forgot about the one-custom-domain-per repo rule as well.

**Comment by nathanweeks** [comment]
> @nathanweeks this one's for you to merge when you've got jekyll-stage.legumeinfo.org set up (in case that wasn't clear). Thanks!

Sorry for dropping the ball. The PR is https://github.com/legumeinfo/jekyll-legumeinfo/pull/33 ; not sure who should review/merge that one?

**Pull request merged**
