### PR TITLE
Add gov shutdown message

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
If Congress fails to pass a spending bill by the morning of December 23, we have been asked to put a notice on our government websites.

Someone among the reviewers, please approve this branch but DO NOT MERGE. If a shutdown is in effect on December 23, then one of us should merge at that time.

### CODE REVIEW

**Review by adf-ncgr — COMMENTED** [review]
not %100 sure but I think this is the sort of thing for which we're supposed to use: [_data/alerts.yml](https://github.com/legumeinfo/jekyll-theme-legumeinfo?tab=readme-ov-file#alertsyml)
@alancleary can you confirm or deny?

**Comment by alancleary** [comment]
> not %100 sure but I think this is the sort of thing for which we're supposed to use: [_data/alerts.yml](https://github.com/legumeinfo/jekyll-theme-legumeinfo?tab=readme-ov-file#alertsyml) @alancleary can you confirm or deny?

It sure is!

**Comment by StevenCannon-USDA** [comment]
@alancleary - please have a look at this attempt.

Based on the code in the theme's `alerts.html`
```
{% if site.data.alerts %}
{% for alert in site.data.alerts %}
<div class="uk-alert-{{ alert.type }}" uk-alert>
  <p>{{ alert.message }}</p>
</div>
{% endfor %}
{% endif %}
```
... it looks to me like I should put a key-value `alert.message: Hey there!!" into _data/alerts.yml ... but that was just giving me a blank div at the top. Hence, my attempt to put the alert in place with some html in the site's `_includes/alerts.html`

If that's not right, please indicate the preferred solution.

**Review by adf-ncgr — CHANGES_REQUESTED** [review]
whoops, I didn't notice your comment before I hastily signaled approval, I expect @alancleary will know what the issue was with using the yml as intended

**Comment by adf-ncgr** [comment]
my guess is that you also needed to specify alert.type

**Comment by alancleary** [comment]
> my guess is that you also needed to specify alert.type

Correct. See the [UIkit docs](https://getuikit.com/docs/alert#style-modifiers) for available types. Note that the `_includes/alerts.html` file should not be overridden if at all possible.

**Comment by StevenCannon-USDA** [comment]
> > my guess is that you also needed to specify alert.type
> 
> Correct. See the [UIkit docs](https://getuikit.com/docs/alert#style-modifiers) for available types. Note that the `_includes/alerts.html` file should not be overridden if at all possible.

I did try that, and it's a fail (blank div at top).
```
cat _data/alerts.yml
---
alert.type: danger
alert.message: "This government website ..."
```

It looks to me like this should resolve to ...
```
<div class="uk-alert-danger" uk-alert>
  <p>This government website ...</p>
</div>
```

... but `{{alert.type}}` and `{{alert.message}}` are empty at the index page.

Punting to @alancleary

**Comment by alancleary** [comment]
> ```
> ---
> alert.type: danger
> alert.message: "This government website ..."
> ```

Drop the `alert.` prefix.

> Punting to @alancleary

Punting back to @StevenCannon-USDA

**Comment by StevenCannon-USDA** [comment]
Thanks, @alancleary . That did the trick. I had also missed seeing the significance of 
`for alert in site.data.alerts`
... which implies that the alert data should be in an array (dash and indent). Flagging @jd-campbell if you want to do the same at jekyll-soybase.

```
---
-
  type: danger
  message: "This government website
```

**Comment by StevenCannon-USDA** [comment]
Closing this PR, since the shutdown drama has ended for this season.

**Pull request closed without merging**
