### PR TITLE
New news post for USDA job ad and new blog post about GO enrichment

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
New news post (at request of USDA leadership), and new blog post (minor variation of one posted at jekyll-soybase)

### CODE REVIEW

**Comment by adf-ncgr** [comment]
It looks like changes should have been propagated to https://jekyll-stage.legumeinfo.org/ but I am not seeing them (despite the github actions having been executed). Am I misremembering how this is supposed to work or does something need to be fixed so that content appears?

**Comment by adf-ncgr** [comment]
Oh, nevermind- I see these aren't on the main branch so I guess only parts of the workflow got triggered (but not the deployment). I'd go ahead with the merge to main and we can make sure it looks good on the stage.

**Review by adf-ncgr — APPROVED** [review]
go for it!

**Comment by StevenCannon-USDA** [comment]
> Oh, nevermind- I see these aren't on the main branch so I guess only parts of the workflow got triggered (but not the deployment). I'd go ahead with the merge to main and we can make sure it looks good on the stage.

Thanks, @adf-ncgr .
As a reminder to us all, Sam made a helpful [workflow about the process for routine content updates](https://github.com/legumeinfo/jekyll-legumeinfo/wiki/Routine-content-updates).

The next steps for me, after merging to main, are ...

6. **Check your work on the staging site** https://jekyll-stage.legumeinfo.org/

7. If corrections need to be made, repeat steps 2 through 6.

8. When you are satisfied with the staging site, **create a new release** with a tag like `2022-05-06.1` on the main repo. This will auto-magically update the production site https://legumeinfo.org/

**Comment by adf-ncgr** [comment]
looks good on stage now- feel free to do the release tagging when you see fit, and thanks for adding this!

**Pull request merged**
