### PR TITLE
updating commit for theme submodule

### PR DESCRIPTION
**Pull request by adf-ncgr**
hopefully fixing issue with stage, not sure if this needed a separate PR, but figured it wouldn't hurt

### CODE REVIEW

**Comment by adf-ncgr** [comment]
bypassing review, hopefully non-controversial....

**Comment by sammyjava** [comment]
Argghhh it's throwing the dreaded `Uncaught (in promise) Error: No form data function provided` while trying to load the gene search page.

**Comment by sammyjava** [comment]
OH! Dev is doing that now! Is something downstream down?

**Comment by sammyjava** [comment]
YUP I broke LegumeMine right when we were looking at this, with the port 8080 update. Will fix, I'm sure that'll fix this. Carry on!

**Comment by sammyjava** [comment]
Something is fouled up with the LegumeMine database. The problem reproduces on lupini-mines, so that's good. I'll re-summarize the object store and take it from there. It was certainly working an hour ago!

**Comment by adf-ncgr** [comment]
looks like it is working again now, at least for the moment. Case closed?

**Comment by adf-ncgr** [comment]
BTW, I was told that the appearance of `Uncaught (in promise) Error: No form data function provided` in the console log is expected at this point. A bug, but one with no functional consequences other than to confuse people seeking to debug other issues (sounds like we have both been bitten by it in the latter way).

**Comment by sammyjava** [comment]
Yeah, I'm not sure if rebuilding the object store helped or if it was just taking forever to compile some stuff because I redeployed all the mines in one swell foop. But I did rebuild the object store. However, the keyword search is broken so I'll rebuild that.

**Comment by adf-ncgr** [comment]
OK, so remind me what the step is where this goes into production- emailing Nathan?

**Comment by sammyjava** [comment]
> OK, so remind me what the step is where this goes into production- emailing Nathan?

Read the Wiki on this repo. :)

**Comment by adf-ncgr** [comment]
perfect, we're finally live...

**Comment by StevenCannon-USDA** [comment]
Yay!! Browsers are back! Looks good in production.
Thank you, @adf-ncgr @sammyjava @ctcncgr @alancleary (at least).

**Pull request merged**
