### PR TITLE
Update GitHub Action workflow to always run & use newer ruby

### PR DESCRIPTION
**Pull request by nathanweeks**
* Run GA build workflow on PR or push to any branch (deploy only for push to default branch)
* Update GA workflow ruby environment for compatibility with theme updates

### CODE REVIEW

**Review by sammyjava — APPROVED** [review]
Looks fine to me, I don't really know how to test it other than pushing it and trying it out, though!

**Comment by alancleary** [comment]
> I don't really know how to test it other than pushing it and trying it out

Fork the repo and enable GitHub automations in the fork.

**Comment by sammyjava** [comment]
Is that the same as enable workflows? Seems like it.

**Comment by nathanweeks** [comment]
I'll add the build-deploy.yml workflow in this PR already ran:
https://github.com/legumeinfo/jekyll-legumeinfo/actions/runs/7625805931

though if course the resulting site wasn't deployed

**Comment by sammyjava** [comment]
It works! Launch away!

**Pull request merged**
