### PR TITLE
Replace bundled UIkit with updated CDN-served versions

### PR DESCRIPTION
**Pull request by nathanweeks**
Rather than bundling a fixed-in-time version of UIkit, suggest pointing to a specific version served via CDN (per https://getuikit.com/docs/installation). This saves space in the git repo, and allows easier updates without unnecessary repo bloat.

This PR also proposes a conservative update of UIkit from 3.6.5 to 3.6.22.

### CODE REVIEW

**Comment by nathanweeks** [comment]
Whoops, I wasn't familiar with how the branches worked on this project. Updated to merge into the `dev` branch.

**Review by sammyjava — APPROVED** [review]

**Comment by nathanweeks** [comment]
@alancleary Not looking to expand the scope of this PR unnecessarily, but is the [theme.css](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/assets/css/theme.css) also one that can be found on a CDN (or based on an existing one that can be linked to with only minor overrides?)

**Comment by sammyjava** [comment]
@alancleary where did theme.css come from? I'm having trouble finding it on the interwebs. UIkit doesn't have such a file. Did it come from a bootstrap theme? If I could track it down I could see if there's an appropriate CDN.

**Comment by alancleary** [comment]
Sorry for the delay on this. I was completely consumed by a workshop I was teaching.

UIkit supports [customization via "themes"](https://getuikit.com/docs/sass#create-a-uikit-theme); theme.css is a custom UIkit theme. I used the theme from the [UIkit website](https://github.com/uikit/uikit-site) as a starting point. However, it has been customized to accommodate LIS's needs. Furthermore, some of the theme's content requires integration with UIkit at compile time, so UIkit should be compiled with the theme (see [How to structure your theme](https://getuikit.com/docs/sass#how-to-structure-your-theme)), i.e. using a pre-compiled UIkit from a CDN in conjunction with the theme breaks some of the theme.

The theme and UIkit files in this repo were compiled by me. The raw LESS files I compiled the theme/UIkit from haven't been committed to a repo but there have been issues for doing so since last summer (legumeinfo/jekyll-theme-legumeinfo#4 and legumeinfo/jekyll-theme-legumeinfo#5). I actually began working on this by converting the theme from LESS to SASS so that it can be compiled by Jekyll's own SASS compiler as part of building the site. The files compile just fine with a regular SASS compiler but Jekyll's compiler was having issues. And that's where I left it since I had more pressing things to work on and this effort didn't have much momentum at the time.

If you don't mind the extra bloat this is going to add to the repo, then I can finish up this work ASAP and we can serve the compiled files via [GitCDN](https://gitcdn.xyz/) or some similar method. Otherwise we'll have to reassess how we're customizing UIkit for our site.

**Comment by alancleary** [comment]
I just revisited the code and found that the reason it wasn't working before is because, despite using the default Jekyll SASS directory, I needed to explicitly specify the SASS directory location in the config file so the import statements would work. I'll clean up the code and add it to the theme repository.

In addition to using Jekyll to build the theme, the big advantage to this approach is that you can add Jekyll variables to your SASS code. So, for example, you could allow people using the theme to customize their site's color scheme via variables in the config file instead of tinkering with SASS code.

**Comment by alancleary** [comment]
OK. The theme repo has been updated to add UIkit as a submodule and compile the theme from SCSS. There's also a couple theme related variables that can now be set from the config file. More can be added in the future if/when other sites need them.

It's worth noting that the UIkit JS and CSS files in the assets directory are now all hard symbolic links to the UIkit submodule. Similarly, the `_sass/uikit` directory is a soft link to the UIkit submodules sass folder.

**Comment by nathanweeks** [comment]
@alancleary : nice! I'm not familiar with the process of compiling the SCSS in the ekyll-theme-legumeinfo repo. Would it be difficult to automate (e.g., via GitHub Actions workflow) and store the resulting CSS in a separate branch for serving via CDN?

**Comment by alancleary** [comment]
> I'm not familiar with the process of compiling the SCSS in the ekyll-theme-legumeinfo repo. Would it be difficult to automate (e.g., via GitHub Actions workflow) and store the resulting CSS in a separate branch for serving via CDN?

Jekyll compiles SASS automatically at build time! Just put a SASS/SCSS file in your assets folder and add some YML front matter to it so Jekyll knows to compile it (the front matter can be empty like the file I added) . By default, Jekyll also compiles anything in the top-level `_sass` directory if it exists. If you want to change the directory Jekyll checks for SASS files OR if the SASS file you put in the assets folder is importing anything, then you need to specify that directory in the `_config.yml` file, which we need to do since we're importing UIkit stuff:
```yml
sass:
    sass_dir: _sass
    style: compressed
```
`style: compressed` isn't required but I added it so the generated CSS file is minimized. That's it. Just add your SASS files and update `_config.yml` so Jekyll knows where to find them.

Here's a link to the Jekyll documentation about all of this: https://jekyllrb.com/docs/assets/

**Comment by alancleary** [comment]
P.S. The precompiled `theme.css` was replaced with the SASS file `uikit-theme.scss`, which Jekyll compiles to `uikit-theme.css`. I renamed it so it's more clear what's going on ;)

**Comment by nathanweeks** [comment]
Thanks @alancleary , that was a big help. I was able to `jekyll build` _site/assets/css/uikit-theme.css in the jekyll-theme-legumeinfo repo (though I had to comment-out the jekyll-datapage-generator sections in the _config.yml to avoid a build-time error---is it necessary to have that plugin in the _config.yml?)

To make the resulting CSS available for jekyll-legumeinfo, does it sound OK to make a GitHub Action workflow (triggered whenever the uikit submodule or assets/css/uikit-theme.scss changes) that builds uikit-theme.css and publishes it to a separate branch (called, e.g., "css"? I'm not sure if there are naming conventions we could follow) to serve via CDN?

(FWIW, regarding CDN druthers, I think [jsdelivr](https://github.com/jsdelivr/jsdelivr) appears to be more viable as a long-term project than [gitcdn.xyz](https://github.com/schme16/gitcdn.xyz))

**Comment by alancleary** [comment]
> To make the resulting CSS available for jekyll-legumeinfo, does it sound OK to make a GitHub Action workflow (triggered whenever the uikit submodule or assets/css/uikit-theme.scss changes) that builds uikit-theme.css and publishes it to a separate branch (called, e.g., "css"? I'm not sure if there are naming conventions we could follow) to serve via CDN?

I'll leave deployment up to you and @sammyjava. I'll note, though, that there are some theme-related variables in the config file now. If we're OK with the default colors in the theme being the LIS colors, then the build process can be added to the theme repo. Otherwise it may be worth replicating it in the jekyll-legumeinfo repo.

> Thanks @alancleary , that was a big help. I was able to jekyll build _site/assets/css/uikit-theme.css in the jekyll-theme-legumeinfo repo (though I had to comment-out the jekyll-datapage-generator sections in the _config.yml to avoid a build-time error---is it necessary to have that plugin in the _config.yml?)

I'm not sure why this would be throwing an error. Were you building with the Docker container? The idea of having it in the theme is to make that functionality work out-of-the-box for anyone who picks up the theme. Feel free to open an issue in the theme repo if you want me to dig into it.

**Comment by nathanweeks** [comment]
> > To make the resulting CSS available for jekyll-legumeinfo, does it sound OK to make a GitHub Action workflow (triggered whenever the uikit submodule or assets/css/uikit-theme.scss changes) that builds uikit-theme.css and publishes it to a separate branch (called, e.g., "css"? I'm not sure if there are naming conventions we could follow) to serve via CDN?
> 
> I'll leave deployment up to you and @sammyjava. I'll note, though, that there are some theme-related variables in the config file now. If we're OK with the default colors in the theme being the LIS colors, then the build process can be added to the theme repo. Otherwise it may be worth replicating it in the jekyll-legumeinfo repo.

I (think I) see: these ones?
https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/_config.yml#L10-L14

@sammyjava : do you have an opinion (replicate @alancleary's uikit/theme work in jekyll-legumeinfo pre-www launch, or build/use what's in jekyll-theme-legumeinfo without customization for now)?

> > Thanks @alancleary , that was a big help. I was able to jekyll build _site/assets/css/uikit-theme.css in the jekyll-theme-legumeinfo repo (though I had to comment-out the jekyll-datapage-generator sections in the _config.yml to avoid a build-time error---is it necessary to have that plugin in the _config.yml?)
> 
> I'm not sure why this would be throwing an error. Were you building with the Docker container? The idea of having it in the theme is to make that functionality work out-of-the-box for anyone who picks up the theme. Feel free to open an issue in the theme repo if you want me to dig into it.

I was building on the (macOS 10.15) host. It could be a documentation issue (not sure); I reproduced the error (in a GitHub Action workflow in a separate branch) & tacked it onto: https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/10#issuecomment-1063913051

**Comment by alancleary** [comment]
> I (think I) see: these ones?
https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/_config.yml#L10-L14

That's them!

> I'm perfectly fine with what we've got right now on jekyll-legumeinfo. It works. I didn't see anything that needed to be fixed. So I'm leaving this up to you two guys @nathanweeks and @alancleary to implement on jekyll-legumeinfo if you feel it's needed.

Keeping things the way they are is definitely an option for roll out, but we'll have to integrate compiling the SCSS at some point. I'm wondering if just adding back the theme to jekyll-legumeinfo is an option.

**Comment by sammyjava** [comment]
It's certainly an option, with the caveat that it'll be up for modifying to update the LIS site. Which is a single-site task, not a theme task. That's why I abandoned it, I had edited pretty much every file in the theme. But I'm happy to put the theme back on the site given what I just said.

**Comment by alancleary** [comment]
> It's certainly an option, with the caveat that it'll be up for modifying to update the LIS site.

Modification or overriding? Overriding is fine but think modifying the theme to accommodate LIS's specific needs isn't what we want.

Another option is to create a branch in the theme that only contains the UIkit/SCSS stuff. LIS could add the theme repo as a submodule, same as before, but stick it to this branch so only the styling comes over. This will still give us the auto-build functionality of Jekyll (including customization of the theme via the config file) but limit what's coming over from the theme to just the styling related content. However, this doesn't use a CDN...

**Comment by alancleary** [comment]
> Then let's leave it as we've got it since the theme isn't appropriate for LIS as I've had to override pretty much everything.

Fixing issue #67 actually required making changes to the <ins>SCSS</ins> file so leaving things as they are probably isn't the solution here.

**Comment by sammyjava** [comment]
Feel free to implement what you want on the LIS site, preserving the current form and function.

**Comment by alancleary** [comment]
OK. @nathanweeks what do you think? Create a branch in the theme for just the styling content and include it as a theme submodule in the Jekyll site, as before, and/or do an automated build sort of thing so the CSS can be loaded from a CDN, or some other solution?

**Comment by nathanweeks** [comment]
@alancleary I don't have a good sense for the most convenient, maintainable, and acceptable-to-all solution at this point (though I don't think the CDN approach). Would it be too much of a maintainability chore to replicate the jekyll-theme-legumeinfo SCSS build infrastructure in jekyll-legumeinfo, so the latter could be self-contained? Or re-introduce jekyll-theme-legumeinfo as a submodule, but track "main" (to avoid having to maintain a separate branch in jekyll-theme-legumeinfo)?

**Comment by alancleary** [comment]
This needs to get done. Unless @nathanweeks speaks up, I'll go ahead and implement the solution I outlined in my previous comment.

**Pull request merged**
