### PR TITLE
Responsive navbar; blog post with an image; README

### PR DESCRIPTION
**Pull request by sammyjava**
Promoting the new navbar code which makes the site "responsive" as well as a modified example blog post which contains an image, plus description of how to write a blog post added to the README (@svengato I promised this so you can write a real blog post with an image).

Note that I've dropped the "category" piece of a blog post, as I don't think the rarity of us posting warrants the extra level of granularity, plus there isn't a generated category-level page, at least with the current code base. I think a post URI like `/blog/2018/09/10/macrosynteny-gcv.html` is just fine.

### CODE REVIEW

**Comment by sammyjava** [comment]
@cann0010 @adf-ncgr @svengato This PR kicks the can in your direction for creating a blog post or two. I've currently got two oldies as examples which must be deleted before launch. I presume we want to have a post or two on the blog when we launch the site. As usual you can see the site here: http://dev.lis.ncgr.org:50030/blog/ Instructions are in the README.

**Comment by svengato** [comment]
> @cann0010 <https://github.com/cann0010> @adf-ncgr
> <https://github.com/adf-ncgr> @svengato <https://github.com/svengato>
> This PR kicks the can in your direction for creating a blog post or two.
> I've currently got two oldies as examples which must be deleted before
> launch. I presume we want to have a post or two on the blog when we launch
> the site. As usual you can see the site here:
> http://dev.lis.ncgr.org:50030/blog/ Instructions are in the README.


I made a ZZBrowse markdown file similar to your examples, then built the
Docker container (from the shokin branch). While the Jekyll container
appears in 'docker images' (though it says it was created 7 months ago), it
is not running at localhost:4000 or visible in 'docker ps'. Using the main
branch, I see the same problem. This is on Fedora 35.

-Sven-

**Comment by nathanweeks** [comment]
@svengato Was  `docker compose up -d` used to start the container? If so, and it didn't end up running, it's possible that the jekyll process errored out somewhere---you could verify with `docker compose logs`.

The soybase/jekyll-soybase repo has a [Makefile](https://github.com/soybase/jekyll-soybase/blob/main/Makefile) with setup instructions for running jekyll on bare-metal macOS, if that's more convenient & easier to troubleshoot (the `make clean` target is sometimes handy in any case).

**Comment by svengato** [comment]
> @svengato <https://github.com/svengato> Was docker compose up -d used to
> start the container? If so, and it didn't end up running, it's possible
> that the jekyll process errored out somewhere---you could verify with docker
> compose logs.


Indeed - the /srv/ directory was empty. I created /srv/jekyll/ by hand but
still get the same error,
jekyll_1  | /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir':
Permission denied @ dir_s_mkdir - /srv/jekyll/.jekyll-cache (Errno::EACCES)

**Comment by sammyjava** [comment]
I don't use docker so can't help with this one. I run jekyll straight up on CentoOS 8 (VM) or Ubuntu (laptop).

**Comment by svengato** [comment]
> I can try installing Ruby and running the site that way.
>

That worked! Now I just have to add the image files. Thanks -

-Sven-

**Pull request merged**
